name: supply_chain_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - gymnasium
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pyomo
  - coincbc
  - scipy
  - cloudpickle
  - importlib-metadata
  - pytorch
  - torchvision
  - pip
  # - cpuonly breaks? switch to cudatoolkit=11.7 on colab
