name: supply_chain_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gymnasium=0.28.1
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pyomo=6.5.0
  - coincbc=2.10.5
  - scipy=1.10.1
  - cloudpickle=2.2.1
  - importlib-metadata=6.0.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cpuonly  # when local, comment out on colab
  - stable-baselines3=1.8.0
  - transformers=4.34.0
